### ISSUE TITLE
How to properly destroy a Display?

### ISSUE THREAD

**Issue by baba43** [TheJoCraftNET/MapEngine#10]
First, thank you very much for this library that is really awesome!

I use the following methods to "destroy" a display:

```
ctx?.receivers()?.forEach { display?.despawn(it) }
ctx?.clearReceivers()
display = null
source?.stop() // FFmpeg source
```

However, this does not seem to be enough. First, the `onMapClick` still fires. Secondly, the servers CPU usage keeps going higher and higher the more times I spawn/despawn a display. So I am sure that I am missing something that must be destroyed.

Would be happy to get some help. Thank you!

**Comment by pianoman911** [comment]
Hello,
there is actually no possibility at the moment. I will make an update.
